variables:
  resource_group_name : "ps-win10-00"
  location : "Canada Central"
  prefix : "ps-windev"
  machine_name : "Win10"
  admin_username : "singh"
  admin_password : "SuperSecureP@ssWord"
  subnet_name : "windows-vm"
  nsg_name : "windows-nsg"
  vnet_name : "ps-devshared-vnet"
  
stages:
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'terraform-install'
      inputs:
        terraformVersion: '0.12.3'
    - task: TerraformTaskV1@0
      displayName: init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'VisualStudio-DevTest(6ba8e616-dc16-4569-90eb-05a53d7896b5)'
        backendAzureRmResourceGroupName: 'ps-devshared-rg'
        backendAzureRmStorageAccountName: 'psdevsharedsa'
        backendAzureRmContainerName: 'sktfcontainer'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV1@0
      displayName: validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
- stage: deploy
  jobs:
    - deployment: deploy_tf
      continueOnError: false
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'terraform-install'
                inputs:
                  terraformVersion: '0.12.3'
              - task: TerraformTaskV1@0
                displayName: init
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'VisualStudio-DevTest(6ba8e616-dc16-4569-90eb-05a53d7896b5)'
                  backendAzureRmResourceGroupName: 'ps-devshared-rg'
                  backendAzureRmStorageAccountName: 'psdevsharedsa'
                  backendAzureRmContainerName: 'sktfcontainer'
                  backendAzureRmKey: 'terraform.tfstate'
              - task: TerraformTaskV1@0
                displayName: plan
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  environmentServiceNameAzureRM: 'VisualStudio-DevTest(6ba8e616-dc16-4569-90eb-05a53d7896b5)'
                  commandOptions: -input=false -var resource_group_name="$(resource_group_name)" -var location="$(location)" -var prefix="$(prefix)" -var machine_name="$(machine_name)" -var admin_username="$(admin_username)" -var admin_password="$(admin_password)" -var subnet_name="$(subnet_name)" -var nsg_name="$(nsg_name)" -var vnet_name="$(vnet_name)"
              - task: TerraformTaskV1@0
                displayName: apply
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  environmentServiceNameAzureRM: 'VisualStudio-DevTest(6ba8e616-dc16-4569-90eb-05a53d7896b5)'